<?php

$labels = array();
$labels['use'] = 'Utilitzar ';
$labels['autosync'] = 'Sincronitzar automaticament al entar';
$labels['authcode'] = 'Codi Auth de Google';
$labels['authcodelink'] = 'Clica aquí para conseguir la autorizació';
$labels['sync'] = 'Sincronitzar Google';
$labels['syncnow'] = 'Comença la sincronització';

$messages = array();
$messages['done'] = 'Fet.';
$messages['contactsfound'] = ' contacte(s) trobats.';
$messages['noauthcode'] = 'Sense codi Auth de Google. La autenticació no és possible.';
$messages['googleauthfailed'] = 'Autenticació fallida.';
$messages['googleunreachable'] = 'Google sembla no estar disponible. Si us plau provi més tard.';
$messages['googleforbidden'] = 'Autenticació no permesa.';
