<?php

$labels = array();
$labels['use'] = 'Použít ';
$labels['autosync'] = 'Automatická synchronizace po přihlášení';
$labels['authcode'] = 'Google autorizační kód';
$labels['authcodelink'] = 'Klikni zde, pro získání autorizačního kódu';
$labels['sync'] = 'Synchronizovat Google';
$labels['syncnow'] = 'Start synchronizace';

$messages = array();
$messages['done'] = 'Hotovo.';
$messages['contactsfound'] = ' kontakt(y) nalezeny.';
$messages['noauthcode'] = 'Není autorizační kód. Ověření není možné.';
$messages['googleunreachable'] = 'Google se zdá být nedostupný. Prosím zkuste to později.';
$messages['googleforbidden'] = 'Chyba ověření!';
