<?php

$labels = array();
$labels['use'] = 'Aktiviere ';
$labels['autosync'] = 'Automatische Synchronisierung beim Login';
$labels['authcode'] = 'Google Authcode';
$labels['authcodelink'] = 'Klicken Sie hier um den Authcode zu erhalten';
$labels['sync'] = 'Sync Google';
$labels['syncnow'] = 'Synchronisation starten';

$messages = array();
$messages['done'] = 'Fertig.';
$messages['contactsfound'] = ' Kontakt(e) gefunden.';
$messages['noauthcode'] = 'Kein Authcode. Authentifizierung nicht möglich.';
$messages['googleunreachable'] = 'Google ist zur Zeit nicht verfügbar. Bitte versuchen Sie es später erneut.';
?>
