<?php

$labels = array();
$labels['use'] = 'Use ';
$labels['autosync'] = 'Auto Sync on Login';
$labels['authcode'] = 'Google Auth Code';
$labels['authcodelink'] = 'Click here to get the auth code';
$labels['sync'] = 'Sync Google';
$labels['syncnow'] = 'Start Synchronisation';

$messages = array();
$messages['done'] = 'Done.';
$messages['contactsfound'] = ' contact(s) found.';
$messages['noauthcode'] = 'No auth code. Authentication not possible.';
$messages['googleauthfailed'] = 'Authentication failed.';
$messages['googleunreachable'] = 'Google seems to be unavailable. Please try again later.';
$messages['googleforbidden'] = 'Authentication failed!';
