<?php

$labels = array();
$labels['use'] = 'Usar ';
$labels['autosync'] = 'Sincronizar automaticamente al entar';
$labels['authcode'] = 'Código Auth de Google';
$labels['authcodelink'] = 'Clica aqui para conseguir la autorización';
$labels['sync'] = 'Sincronizar Google';
$labels['syncnow'] = 'Comenza la sincronización';

$messages = array();
$messages['done'] = 'Hecho.';
$messages['contactsfound'] = ' contacto(s) encontrados.';
$messages['noauthcode'] = 'Sin código Auth de Google. Autenticación no posible.';
$messages['googleauthfailed'] = 'Autenticación fallida.';
$messages['googleunreachable'] = 'Google parece no estar dispoible. Por favor pruebe más tarde.';
$messages['googleforbidden'] = 'Autenticación no permitida.';
