<?php

$labels = array();
$labels['use'] = 'Usa ';
$labels['autosync'] = 'Sincronizzazione automatica all\'accesso';
$labels['authcode'] = 'Codice di autorizzazione di Google';
$labels['authcodelink'] = 'Clicca qui per ottenere il codice di autorizzazione';
$labels['sync'] = 'Sincronizza i contatti Google';
$labels['syncnow'] = 'Inizia la sincronizzazione';

$messages = array();
$messages['done'] = 'Fatto.';
$messages['contactsfound'] = ' contatti trovati.';
$messages['noauthcode'] = 'Nessun codice di autorizzazione. L\'autenticazione non è possibile.';
$messages['googleunreachable'] = 'Google sembra non essere raggiungibile. Prova più tardi.';
$messages['googleforbidden'] = 'Autenticazione fallita!';
