<?php

$labels = array();
$labels['use'] = 'Użyj ';
$labels['autosync'] = 'Automatyczna synchronizacja podczas logowania';
$labels['authcode'] = 'Kod autoryzacji Google';
$labels['authcodelink'] = 'Kliknij to aby uzyskać kod autoryzacji Google';
$labels['sync'] = 'Synchronizacja Google';
$labels['syncnow'] = 'Start synchronizacji';

$messages = array();
$messages['done'] = 'Zrobione.';
$messages['contactsfound'] = ' znalezione kontakty.';
$messages['noauthcode'] = 'Brak kodu autoryzacji. Autentykacja niemożliwa.';
$messages['googleunreachable'] = 'Wydaje się, że Google seems są nieosiągalne. Spróbuj później.';
$messages['googleforbidden'] = 'Autentykacja nie udana!';
?>
